spring:
  datasource:
    url: ${db-url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db-username}
    password: ${db-password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

# JWT Configuration
jwt:
  secret-key: ${jwt-secret-key}
  access-token-expires-in: ${jwt-access-ttl}  # (ms)
  refresh-token-expires-in: ${jwt-refresh-ttl}  # (ms)

# Refresh Token Configuration
refresh-token:
  ttl-days: 8
  cleanup-cron: "0 0 3 * * *"  # 3AM

# Frontend Configuration
frontend:
  url: http://localhost:5173
  cookie:
    secure: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

#OpenTelemetry : off
otel:
  sdk:
    disabled: true
management:
  otlp:
    metrics:
      export:
        enabled: false
    logging:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
